name: Deploy

on:
  push:
    branches:
      - main
 concurrency:
  group: deployment
  cancel-in-progress: true
  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - run: sleep 60
